import 'dotenv/config'; import {connectDB} from './config/db.js'; import FoodDonation from './models/FoodDonation.js'; import ShelterRequest from './models/ShelterRequest.js'; import Volunteer from './models/Volunteer.js'; import RescueMission from './models/RescueMission.js'; import AppNotification from './models/AppNotification.js';
const base=Date.now(),iso=(mins:number)=>new Date(base+mins*60000).toISOString();
const loc=(lat:number,lng:number,area:string,address=area)=>({lat,lng,area,address});
async function seed(){await connectDB(process.env.MONGODB_URI||'');if(process.env.SEED_ALLOW_DESTRUCTIVE!=='true'){throw new Error('Seed replaces all demo collections. Set SEED_ALLOW_DESTRUCTIVE=true in server/.env only when you intend to erase and reseed this database.');}if(process.env.NODE_ENV==='production')throw new Error('Destructive demo seeding is disabled in production.');await Promise.all([FoodDonation.deleteMany({}),ShelterRequest.deleteMany({}),Volunteer.deleteMany({}),RescueMission.deleteMany({}),AppNotification.deleteMany({})]);
const donations=[
 {donorName:'Grand Amer Banquets',donorType:'Event Banquet',donorContact:'+91 90000 01001',foodName:'Paneer curry and jeera rice',category:'Cooked Meals',dietary:'Vegetarian',quantityMeals:80,weightKg:32,preparedTime:iso(-30),pickupWindowStart:iso(0),pickupDeadline:iso(180),location:loc(26.985,75.851,'Amer Road','Amer Road, Jaipur'),status:'Pending Match',packaging:'Sealed food-grade trays',storageTemp:'Hot (>60°C)',createdAt:iso(-5)},
 {donorName:'Pink City Grand Hotel',donorType:'Hotel',donorContact:'+91 90000 01002',foodName:'Assorted breads and buns',category:'Bakery & Bread',dietary:'Vegan',quantityMeals:45,weightKg:12,preparedTime:iso(-60),pickupWindowStart:iso(0),pickupDeadline:iso(240),location:loc(26.916,75.820,'Bani Park'),status:'Pending Match',packaging:'Paper bags in clean crates',storageTemp:'Room Temp (20-25°C)',createdAt:iso(-15)},
 {donorName:'Lotus Courtyard Kitchen',donorType:'Restaurant',donorContact:'+91 90000 01003',foodName:'Seasonal fresh vegetables',category:'Fresh Produce',dietary:'Vegan',quantityMeals:60,weightKg:24,preparedTime:iso(-20),pickupWindowStart:iso(10),pickupDeadline:iso(210),location:loc(26.905,75.806,'C-Scheme'),status:'Pending Match',packaging:'Vented produce boxes',storageTemp:'Chilled (<5°C)',createdAt:iso(-25)},
 {donorName:'Mansarovar Campus Mess',donorType:'Hostel',donorContact:'+91 90000 01004',foodName:'Dal, rice and chapati',category:'Cooked Meals',dietary:'Vegetarian',quantityMeals:120,weightKg:48,preparedTime:iso(-25),pickupWindowStart:iso(0),pickupDeadline:iso(120),location:loc(26.857,75.764,'Mansarovar'),status:'Pending Match',packaging:'Lidded steel carriers',storageTemp:'Hot (>60°C)',createdAt:iso(-35)},
 {donorName:'Saffron Courtyard Events',donorType:'Event Banquet',donorContact:'+91 90000 01005',foodName:'Packed snack boxes',category:'Packaged & Dry',dietary:'Jain',quantityMeals:70,weightKg:21,preparedTime:iso(-90),pickupWindowStart:iso(0),pickupDeadline:iso(300),location:loc(26.898,75.842,'Jhotwara'),status:'Pending Match',packaging:'Individually sealed boxes',storageTemp:'Room Temp (20-25°C)',createdAt:iso(-45)},
 {donorName:'Peach Tree Cafeteria',donorType:'Corporate Cafeteria',donorContact:'+91 90000 01006',foodName:'Fruit and yogurt cups',category:'Dairy & Beverages',dietary:'Vegetarian',quantityMeals:35,weightKg:14,preparedTime:iso(-15),pickupWindowStart:iso(0),pickupDeadline:iso(90),location:loc(26.878,75.807,'Tonk Road'),status:'Pending Match',packaging:'Chilled sealed cups',storageTemp:'Chilled (<5°C)',createdAt:iso(-55)}
] as const;
const ds=await FoodDonation.insertMany(donations);
const requests=[
 {shelterName:'Udaan Community Kitchen',shelterCode:'UDN-JPR-01',contactPerson:'Asha Sharma',phone:'+91 91111 02001',location:loc(26.922,75.826,'Bani Park'),requiredMeals:100,receivedMeals:0,dietaryPreference:'Vegetarian',urgency:'Critical',deadlineTime:iso(120),status:'Open',beneficiaryCount:95},
 {shelterName:'Sakhi Girls Home',shelterCode:'SGH-JPR-02',contactPerson:'Meera Joshi',phone:'+91 91111 02002',location:loc(26.891,75.815,'C-Scheme'),requiredMeals:55,receivedMeals:0,dietaryPreference:'Vegetarian',urgency:'High',deadlineTime:iso(180),status:'Open',beneficiaryCount:50},
 {shelterName:'Nayi Disha Learning Centre',shelterCode:'NDL-JPR-03',contactPerson:'Ravi Meena',phone:'+91 91111 02003',location:loc(26.852,75.782,'Mansarovar'),requiredMeals:140,receivedMeals:0,dietaryPreference:'Jain',urgency:'High',deadlineTime:iso(210),status:'Open',beneficiaryCount:130},
 {shelterName:'Seva Path Night Shelter',shelterCode:'SPN-JPR-04',contactPerson:'Imran Khan',phone:'+91 91111 02004',location:loc(26.927,75.844,'Shastri Nagar'),requiredMeals:75,receivedMeals:0,dietaryPreference:'Non-Vegetarian',urgency:'Medium',deadlineTime:iso(240),status:'Open',beneficiaryCount:70},
 {shelterName:'Aarambh Child Support Home',shelterCode:'ACS-JPR-05',contactPerson:'Kavita Rao',phone:'+91 91111 02005',location:loc(26.909,75.792,'Civil Lines'),requiredMeals:45,receivedMeals:0,dietaryPreference:'Vegan',urgency:'Critical',deadlineTime:iso(90),status:'Open',beneficiaryCount:42},
 {shelterName:'Maitri Senior Care',shelterCode:'MSC-JPR-06',contactPerson:'Sunil Verma',phone:'+91 91111 02006',location:loc(26.879,75.858,'Jhotwara'),requiredMeals:90,receivedMeals:0,dietaryPreference:'Vegetarian',urgency:'Low',deadlineTime:iso(360),status:'Open',beneficiaryCount:82}
] as const;
const ss=await ShelterRequest.insertMany(requests);
const vs=await Volunteer.insertMany([{name:'Priya Meena',phone:'+91 92222 03001',vehicleType:'Electric Two-Wheeler',vehicleNumber:'RJ14 EV 1201',rating:4.9,completedRescues:42,status:'Available',currentLocation:{lat:26.91,lng:75.82,area:'Bani Park'}},{name:'Arjun Singh',phone:'+91 92222 03002',vehicleType:'Cargo Van',vehicleNumber:'RJ14 CA 2202',rating:4.8,completedRescues:61,status:'Available',currentLocation:{lat:26.95,lng:75.84,area:'Shastri Nagar'}},{name:'Farah Khan',phone:'+91 92222 03003',vehicleType:'Auto Rickshaw',vehicleNumber:'RJ14 AR 3303',rating:4.7,completedRescues:28,status:'Available',currentLocation:{lat:26.89,lng:75.80,area:'C-Scheme'}},{name:'Dev Rathore',phone:'+91 92222 03004',vehicleType:'Motorcycle',vehicleNumber:'RJ14 MC 4404',rating:4.6,completedRescues:19,status:'Available',currentLocation:{lat:26.86,lng:75.77,area:'Mansarovar'}},{name:'Nisha Jain',phone:'+91 92222 03005',vehicleType:'Car',vehicleNumber:'RJ14 CR 5505',rating:5,completedRescues:35,status:'Available',currentLocation:{lat:26.92,lng:75.85,area:'Jhotwara'}}]);
const d=ds[0],s=ss[0],v=vs[0];d.status='In Transit';d.matchedShelterId=String(s.id);d.matchedShelterName=s.shelterName;d.assignedVolunteerId=String(v.id);d.assignedVolunteerName=v.name;await d.save();s.receivedMeals=35;s.status='Partially Fulfilled';await s.save();v.status='On Active Rescue';await v.save();
await RescueMission.create({rescueCode:'SSR-24001',donationId:String(d.id),shelterRequestId:String(s.id),donorName:d.donorName,donorLocation:d.location,shelterName:s.shelterName,shelterLocation:s.location,volunteerId:String(v.id),volunteerName:v.name,volunteerPhone:v.phone,volunteerVehicle:v.vehicleType,volunteerRating:v.rating,mealsCount:35,foodName:d.foodName,category:d.category,dietary:d.dietary,status:'In Transit',etaMinutes:12,totalDistanceKm:4.2,pickupCompletedTime:iso(-18),timeline:[{time:iso(-25),title:'Volunteer assigned',description:`${v.name} accepted the rescue`,status:'completed'},{time:iso(-18),title:'Food picked up',description:'Pickup verified at the donor location',status:'completed'},{time:iso(-10),title:'In transit',description:'Volunteer is heading to the shelter',status:'current'}],routeCoordinates:[[d.location.lat,d.location.lng],[s.location.lat,s.location.lng]],currentVolunteerCoord:[26.91,75.82],verificationOtp:'4826'});
await AppNotification.insertMany([{title:'High Priority Shelter Need',message:'Aarambh Child Support Home needs 45 meals before the next service window.',timestamp:iso(-5),type:'urgent',read:false,actionUrl:'/requests'},{title:'Smart Match Ready',message:'A new donation can serve nearby Jaipur shelter requests.',timestamp:iso(-18),type:'match',read:false,actionUrl:'/smart-match'},{title:'Volunteer Dispatched',message:`${v.name} is completing a food rescue route.`,timestamp:iso(-25),type:'dispatch',read:true},{title:'Pickup Verified',message:'A cooked meal donation was collected and is in transit.',timestamp:iso(-18),type:'pickup',read:true},{title:'Delivery Completed Successfully',message:'A previous rescue delivered 45 meals to a Jaipur partner shelter.',timestamp:iso(-60),type:'delivery',read:true}]);
console.log(`Seeded ${ds.length} donations, ${ss.length} shelter requests, ${vs.length} volunteers, 1 active mission and 5 notifications.`);await (await import('mongoose')).default.disconnect();}
seed().catch(async e=>{console.error('Seed failed:',e);await (await import('mongoose')).default.disconnect();process.exitCode=1;});
